/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author ACER
 */
public class DetailMakanan extends javax.swing.JFrame {

    /**
     * Creates new form DetailMakanan
     */
    public DetailMakanan() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gambarMenu = new javax.swing.JLabel();
        deskripsi = new javax.swing.JLabel();
        namaPaket = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gambarMenu.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        gambarMenu.setForeground(new java.awt.Color(204, 255, 0));
        gambarMenu.setText("PAKET");
        getContentPane().add(gambarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 260, 340));

        deskripsi.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        deskripsi.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(deskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 260, 20));

        namaPaket.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        namaPaket.setForeground(new java.awt.Color(255, 255, 255));
        namaPaket.setText("PAKET");
        getContentPane().add(namaPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 260, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Username.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 960));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailMakanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deskripsi;
    private javax.swing.JLabel gambarMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel namaPaket;
    // End of variables declaration//GEN-END:variables
}
