/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import ConnectionMySQL.ConnectionDB;
import java.awt.Color;
import java.awt.Image;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.sql.*;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ACER
 */
public class HomeUserMakanan extends javax.swing.JFrame {
    private String kamar = null;
    Connection koneksi;
    Statement st = null;
    ResultSet rs = null;
    DefaultTableModel tabelMenu = null;
    DefaultTableModel tabelUntukKeranjang = null;
    ArrayList<ImageIcon> imageList = new ArrayList<>();
    ArrayList<String> daftarKeranjang = new ArrayList<>();
    int row;
    
    int total = 0;
    
    Integer row2 = null;
    
    int addKurang = 0;

    /**
     * Creates new form HomeUserMakanan
     */
    public HomeUserMakanan() {
        this.koneksi = ConnectionDB.getInstance().getConnection();
        initComponents();
        getData("Makanan");
        this.gbr1.setIcon(this.imageList.get(0));
        this.hrg1.setText(tabelTabel.getValueAt(0, 1).toString());
        this.nmMKn1.setText(tabelTabel.getValueAt(0, 0).toString());
        this.tabelTabel.setBackground(new Color(255, 255, 255));
        this.setVisible(false);
        this.panelKeranjang.setVisible(false);
    }
    
    String getNomorKamar(){
        return this.kamar;
    }
    
    void setNomorKamar(String kamar){
        this.kamar = kamar;
        this.nomorKamar.setText(this.kamar);
    }
    

    
    void getData(String param){
        this.imageList.clear();
        tabelMenu = (DefaultTableModel) this.tabelTabel.getModel();
        tabelMenu.setRowCount(0);
        try {
            this.st = this.koneksi.createStatement();
            String query = String.format("select * from menu where jenis = \"%s\"", param);
            System.out.println("query : " + query);
            this.rs = st.executeQuery(query);
            while(rs.next()){
                byte[] imageData= null;
                if(rs.getString("status").equals("Tidak Tersedia")){
                    imageData = rs.getBytes("gambar_dis");
                }else{
                    imageData = rs.getBytes("gambar");
                }
                tabelMenu.addRow(new Object[]{rs.getString("nama"),rs.getString("harga"),rs.getString("status"),rs.getString("deskripsi")});
                if(imageData != null){
                    ImageIcon imageIcon = new ImageIcon(scaleImage(imageData, 420, 320));
                    this.imageList.add(imageIcon);
                }else{
                    this.imageList.add(null);
                }
            }
        
        this.tabelTabel.setRowHeight(40);
            
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    private Image scaleImage(byte[] imageData, int width, int height) {
        try {
            Image image = ImageIO.read(new ByteArrayInputStream(imageData));
            return image.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tombolLogout = new javax.swing.JButton();
        panelKeranjang = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelKeranjang = new javax.swing.JTable();
        tombolKurangiMakanan = new javax.swing.JButton();
        tombolAddMakanan = new javax.swing.JButton();
        jumlah = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        totalHarga = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTabel = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        nmMKn1 = new javax.swing.JLabel();
        tombolTambahPesanan = new javax.swing.JButton();
        gbr1 = new javax.swing.JLabel();
        hrg1 = new javax.swing.JLabel();
        jumlahPesanan = new javax.swing.JLabel();
        menuCamilan = new javax.swing.JButton();
        menuMakanan = new javax.swing.JButton();
        riwayat = new javax.swing.JButton();
        keranjang = new javax.swing.JButton();
        menuMinuman = new javax.swing.JButton();
        nomorKamar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tombolLogout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tombolLogout.setText("Logout");
        tombolLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(tombolLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 1010, 100, 40));

        panelKeranjang.setBackground(new java.awt.Color(255, 51, 0));
        panelKeranjang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Harga", "Jumlah", "Kamar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelKeranjang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKeranjangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabelKeranjangMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tabelKeranjang);
        if (tabelKeranjang.getColumnModel().getColumnCount() > 0) {
            tabelKeranjang.getColumnModel().getColumn(0).setResizable(false);
            tabelKeranjang.getColumnModel().getColumn(1).setResizable(false);
            tabelKeranjang.getColumnModel().getColumn(2).setResizable(false);
            tabelKeranjang.getColumnModel().getColumn(3).setResizable(false);
        }

        panelKeranjang.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 760, 420));

        tombolKurangiMakanan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tombolKurangiMakanan.setText("<");
        tombolKurangiMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolKurangiMakananActionPerformed(evt);
            }
        });
        panelKeranjang.add(tombolKurangiMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 40, -1));

        tombolAddMakanan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tombolAddMakanan.setText(">");
        tombolAddMakanan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tombolAddMakananItemStateChanged(evt);
            }
        });
        tombolAddMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolAddMakananActionPerformed(evt);
            }
        });
        panelKeranjang.add(tombolAddMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 40, -1));

        jumlah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jumlah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelKeranjang.add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 70, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Total Harga :");
        panelKeranjang.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 70, 120, -1));

        totalHarga.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        panelKeranjang.add(totalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 70, 190, 30));

        getContentPane().add(panelKeranjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 1230, 840));

        tabelTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Harga", "Status", "Deskripsi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelTabel.setGridColor(new java.awt.Color(255, 255, 255));
        tabelTabel.getTableHeader().setReorderingAllowed(false);
        tabelTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelTabel);
        if (tabelTabel.getColumnModel().getColumnCount() > 0) {
            tabelTabel.getColumnModel().getColumn(0).setResizable(false);
            tabelTabel.getColumnModel().getColumn(0).setHeaderValue("Nama");
            tabelTabel.getColumnModel().getColumn(1).setResizable(false);
            tabelTabel.getColumnModel().getColumn(1).setHeaderValue("Harga");
            tabelTabel.getColumnModel().getColumn(2).setResizable(false);
            tabelTabel.getColumnModel().getColumn(2).setHeaderValue("Status");
            tabelTabel.getColumnModel().getColumn(3).setResizable(false);
            tabelTabel.getColumnModel().getColumn(3).setHeaderValue("Deskripsi");
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 600, 1190, 420));

        jPanel1.setBackground(new java.awt.Color(204, 0, 204));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/detail.png"))); // NOI18N
        jButton8.setContentAreaFilled(false);

        nmMKn1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        nmMKn1.setForeground(new java.awt.Color(255, 255, 255));
        nmMKn1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nmMKn1.setText("MAKANAN");
        nmMKn1.setAlignmentY(0.0F);

        tombolTambahPesanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tambah.png"))); // NOI18N
        tombolTambahPesanan.setContentAreaFilled(false);
        tombolTambahPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTambahPesananActionPerformed(evt);
            }
        });

        gbr1.setText("jLabel5");

        hrg1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        hrg1.setForeground(new java.awt.Color(255, 255, 255));
        hrg1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hrg1.setText("HARGA");
        hrg1.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gbr1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nmMKn1)
                    .addComponent(hrg1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tombolTambahPesanan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8)
                        .addGap(29, 29, 29)
                        .addComponent(jumlahPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(995, 995, 995))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gbr1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nmMKn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hrg1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tombolTambahPesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jumlahPesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 1190, 290));

        menuCamilan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cemil b.png"))); // NOI18N
        menuCamilan.setToolTipText("");
        menuCamilan.setAlignmentY(0.0F);
        menuCamilan.setContentAreaFilled(false);
        menuCamilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCamilanActionPerformed(evt);
            }
        });
        getContentPane().add(menuCamilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 680, -1, -1));

        menuMakanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/makan w.png"))); // NOI18N
        menuMakanan.setToolTipText("");
        menuMakanan.setAlignmentY(0.0F);
        menuMakanan.setContentAreaFilled(false);
        menuMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMakananActionPerformed(evt);
            }
        });
        getContentPane().add(menuMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, -1, -1));

        riwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Riwayat Pesanan b.png"))); // NOI18N
        riwayat.setToolTipText("");
        riwayat.setAlignmentY(0.0F);
        riwayat.setContentAreaFilled(false);
        riwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riwayatActionPerformed(evt);
            }
        });
        getContentPane().add(riwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 880, -1, -1));

        keranjang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/keranjang b.png"))); // NOI18N
        keranjang.setToolTipText("");
        keranjang.setAlignmentY(0.0F);
        keranjang.setContentAreaFilled(false);
        keranjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keranjangActionPerformed(evt);
            }
        });
        getContentPane().add(keranjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 780, -1, -1));

        menuMinuman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minum b.png"))); // NOI18N
        menuMinuman.setToolTipText("");
        menuMinuman.setAlignmentY(0.0F);
        menuMinuman.setContentAreaFilled(false);
        menuMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMinumanActionPerformed(evt);
            }
        });
        getContentPane().add(menuMinuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, -1, -1));

        nomorKamar.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        nomorKamar.setForeground(new java.awt.Color(255, 255, 255));
        nomorKamar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomorKamar.setText("KAMAR");
        nomorKamar.setAlignmentY(0.0F);
        getContentPane().add(nomorKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 320, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg home user makanan.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCamilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCamilanActionPerformed
        // TODO add your handling code here:
        menuMakanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/makan b.png")));
        menuMinuman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minum b.png")));
        menuCamilan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/camil w.png")));
        keranjang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/keranjang b.png")));
        riwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Riwayat Pesanan b.png")));
        this.getData("Cemilan");
        this.gbr1.setIcon(this.imageList.get(0));
        this.hrg1.setText(tabelTabel.getValueAt(0, 1).toString());
        this.nmMKn1.setText(tabelTabel.getValueAt(0, 0).toString());
        this.panelKeranjang.setVisible(false);
        this.jPanel1.setVisible(true);
        this.jScrollPane1.setVisible(true);
    }//GEN-LAST:event_menuCamilanActionPerformed

    private void menuMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMakananActionPerformed
        // TODO add your handling code here:
        menuMakanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/makan w.png")));
        menuMinuman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minum b.png")));
        menuCamilan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cemil b.png")));
        keranjang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/keranjang b.png")));
        riwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Riwayat Pesanan b.png")));
        this.getData("Makanan");
        this.gbr1.setIcon(this.imageList.get(0));
        this.hrg1.setText(tabelTabel.getValueAt(0, 1).toString());
        this.nmMKn1.setText(tabelTabel.getValueAt(0, 0).toString());
        this.panelKeranjang.setVisible(false);
        this.jPanel1.setVisible(true);
        this.jScrollPane1.setVisible(true);
    }//GEN-LAST:event_menuMakananActionPerformed

    private void riwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riwayatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_riwayatActionPerformed

    private void keranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keranjangActionPerformed
        // TODO add your handling code here:
        menuMakanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/makan b.png")));
        menuMinuman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minum b.png")));
        menuCamilan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cemil b.png")));
        keranjang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/keranjang w.png")));
        riwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Riwayat Pesanan b.png")));
        this.panelKeranjang.setVisible(true);
        this.jPanel1.setVisible(false);
        this.jScrollPane1.setVisible(false);
        
    }//GEN-LAST:event_keranjangActionPerformed

    private void menuMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMinumanActionPerformed
        // TODO add your handling code here:
//        this.dispose();
//        this.hmus = new HomeUserMinuman();
//        this.hmus.setVisible(true);
//        this.hmus.setNomorKamar(kamar);
        menuMakanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/makan b.png")));
        menuMinuman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minum w.png")));
        menuCamilan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cemil b.png")));
        keranjang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/keranjang b.png")));
        riwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Riwayat Pesanan b.png")));
        this.getData("Minuman");
        this.gbr1.setIcon(this.imageList.get(0));
        this.hrg1.setText(tabelTabel.getValueAt(0, 1).toString());
        this.nmMKn1.setText(tabelTabel.getValueAt(0, 0).toString());
        this.panelKeranjang.setVisible(false);
        this.jPanel1.setVisible(true);
        this.jScrollPane1.setVisible(true);
    }//GEN-LAST:event_menuMinumanActionPerformed

    private void tabelTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTabelMouseClicked
        // TODO add your handling code here:
        int row = tabelTabel.getSelectedRow();
        this.gbr1.setIcon(this.imageList.get(row));
        this.hrg1.setText(tabelTabel.getValueAt(row, 1).toString());
        this.nmMKn1.setText(tabelTabel.getValueAt(row, 0).toString());
    }//GEN-LAST:event_tabelTabelMouseClicked

    private void tombolTambahPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolTambahPesananActionPerformed
        // TODO add your handling code here:
        this.tabelUntukKeranjang = (DefaultTableModel) this.tabelKeranjang.getModel();

        this.tabelUntukKeranjang.addRow(new Object[]{this.nmMKn1.getText(), this.hrg1.getText(), 1, this.getNomorKamar()});
        this.total = 0;
        for (int i = 0; i < tabelUntukKeranjang.getRowCount(); i++) {
                int jumlah = (Integer) this.tabelUntukKeranjang.getValueAt(i, 2);
                int harga = Integer.valueOf(this.tabelUntukKeranjang.getValueAt(i, 1).toString());
                total += jumlah * harga;
            }
        this.totalHarga.setText(String.valueOf(total));
    }//GEN-LAST:event_tombolTambahPesananActionPerformed

    private void tombolLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolLogoutActionPerformed
        // TODO add your handling code here:
        Login logout = new Login();
        logout.setVisible(true);
        dispose();
    }//GEN-LAST:event_tombolLogoutActionPerformed

    private void tombolKurangiMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKurangiMakananActionPerformed
        // TODO add your handling code here:
        if(this.row2 != null){
        if(this.addKurang < 0){
            JOptionPane.showMessageDialog(this, "Jumlah minimal 0");
        }else{
            --addKurang;
            this.jumlah.setText(String.valueOf(addKurang));
            this.tabelUntukKeranjang.setValueAt(addKurang, row2, 2);
            
            int total = 0;
            for (int i = 0; i < tabelUntukKeranjang.getRowCount(); i++) {
                int jumlah = (Integer) this.tabelUntukKeranjang.getValueAt(i, 2);
                int harga = Integer.valueOf(this.tabelUntukKeranjang.getValueAt(i, 1).toString());
                total += jumlah * harga;
            }
            
            this.totalHarga.setText(String.valueOf(total));
        }
        
    } else {
        JOptionPane.showMessageDialog(this, "Pilih menu dahulu!");
    }
        
    }//GEN-LAST:event_tombolKurangiMakananActionPerformed

    private void tabelKeranjangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKeranjangMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelKeranjangMouseEntered

    private void tabelKeranjangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKeranjangMouseClicked
        // TODO add your handling code here:
        this.row2 = tabelKeranjang.getSelectedRow();
        this.jumlah.setText(String.valueOf(tabelKeranjang.getValueAt(row, 2)));
        this.addKurang = Integer.valueOf(this.jumlah.getText());
    }//GEN-LAST:event_tabelKeranjangMouseClicked

    private void tombolAddMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolAddMakananActionPerformed
        // TODO add your handling code here:
        if(this.row2 != null){
        if(this.addKurang < 0){
            JOptionPane.showMessageDialog(this, "Jumlah minimal 0");
        }else{
            ++addKurang;
            this.jumlah.setText(String.valueOf(addKurang));
            this.tabelUntukKeranjang.setValueAt(addKurang, row2, 2);
            
            int total = 0;
            for (int i = 0; i < tabelUntukKeranjang.getRowCount(); i++) {
                int jumlah = (Integer) this.tabelUntukKeranjang.getValueAt(i, 2);
                int harga = Integer.valueOf(this.tabelUntukKeranjang.getValueAt(i, 1).toString());
                total += jumlah * harga;
            }
            
            this.totalHarga.setText(String.valueOf(total));
        }
        
    } else {
        JOptionPane.showMessageDialog(this, "Pilih menu dahulu!");
    }
        
        
    }//GEN-LAST:event_tombolAddMakananActionPerformed

    private void tombolAddMakananItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tombolAddMakananItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tombolAddMakananItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUserMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUserMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUserMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUserMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeUserMakanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gbr1;
    private javax.swing.JLabel hrg1;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jumlah;
    private javax.swing.JLabel jumlahPesanan;
    private javax.swing.JButton keranjang;
    private javax.swing.JButton menuCamilan;
    private javax.swing.JButton menuMakanan;
    private javax.swing.JButton menuMinuman;
    private javax.swing.JLabel nmMKn1;
    private javax.swing.JLabel nomorKamar;
    private javax.swing.JPanel panelKeranjang;
    private javax.swing.JButton riwayat;
    private javax.swing.JTable tabelKeranjang;
    private javax.swing.JTable tabelTabel;
    private javax.swing.JButton tombolAddMakanan;
    private javax.swing.JButton tombolKurangiMakanan;
    private javax.swing.JButton tombolLogout;
    private javax.swing.JButton tombolTambahPesanan;
    private javax.swing.JLabel totalHarga;
    // End of variables declaration//GEN-END:variables
}
